### ISSUE TITLE
Suggested workflow to not break the changelog

### ISSUE THREAD

**Issue by jrson83** [bscotch/jslib#4]
Hello @adam-coster,

I'm sorry to bother again with just a question and not a real issue, but after bumping the first time, I experience an issue with some generated changelogs. I double checked the commit history of this repo, to see if I can understand your workflow, since I think there is something wrong with [mine](https://github.com/inertiajs-revamped/inertia/commits/main/). For the [core](https://github.com/inertiajs-revamped/inertia/blob/main/packages/core/CHANGELOG.md) package it seems fine, but for the other packages, it dropped `v0.0.1` from changelogs.

**What I understand from your workflow:**

1. Commit & merge some changes.
2. `bump` version, individual or for multiple packages.
3. Generate, commit & merge changelog only for `one` package (since every `chore: update changelog` includes only 1 package).
4. Create git `tag` which is based on the `commit` update changelog. Push tag & publish ?

Since I do not understand, how exactly you tag/push, could you please tell me your workflow? I would be pleased 😁 

Like when todo:

```sh
git tag @inertiajs-revamped/core@0.0.2
git push origin @inertiajs-revamped/core@0.0.2
pnpm publish
```

**Comment by adam-coster** [comment]
Version info can come from two places: the `version` field in the `package.json`, and the git tags. My workflow tools generally use the git tags as the source of truth where possible, since the `package.json` can have its version *decremented* during a merge from an older branch, for example.

My approach is almost what you said, except that tagging comes before changelog generation:

1. Make commits
2. `bump` the version for all impacted packages, which includes updating the `package.json` and adding version tags
3. Update & commit changelogs (single commit)
4. Publish

I only make one commit after a bump for *all* changelog updates, it's just that in this monorepo I usually only change one project at a time. You can see this in a [much-busier repo](https://github.com/bscotch/stitch/commits/develop/).

**Comment by jrson83** [comment]
After failing another release and investigating in the issue, I noticed that I accidently tagged the wrong commit for 4 packages on my initial release.

![image](https://github.com/bscotch/jslib/assets/45284565/046ea875-cbfb-40ed-824a-4a9b42b37de2)

After I force pushed the tags to the `changelogs` commit, the changelog generator was able to generate all version related changelogs properly.

![image](https://github.com/bscotch/jslib/assets/45284565/5e0ac449-fc26-4fa8-9bad-8d7dca432058)

Also I just released a new version for every package and the generator [worked great](https://github.com/inertiajs-revamped/inertia/commit/f2c82352660f965acd357533f77b75e72c042f57)!

@adam-coster thank you for taking the time to explain your workflow.
